#ifndef COLORS_H_
#define COLORS_H_

#define OSCILLOSCOPE_COLOR_BACKGROUND      0x000000
#define OSCILLOSCOPE_COLOR_GRID            0xA00000
#define OSCILLOSCOPE_COLOR_ZERO            0xFF40FF
#define OSCILLOSCOPE_COLOR_CHANNEL_1       0xF8F800
#define OSCILLOSCOPE_COLOR_CHANNEL_2       0x00E8F8
#define OSCILLOSCOPE_COLOR_CHANNEL_1_TEXT  0xFFFF00
#define OSCILLOSCOPE_COLOR_CHANNEL_2_TEXT  0x00FFFF
#define OSCILLOSCOPE_COLOR_UNITS           0xFFC000
#define OSCILLOSCOPE_COLOR_LOGO            0x0000BF
#define OSCILLOSCOPE_COLOR_LOGO_BACKGROUND 0xFFF0FF
#define OSCILLOSCOPE_COLOR_FREQUENCY       0xFF0080
#define OSCILLOSCOPE_COLOR_TRIGGER         0xBFBFBF

#endif /* COLORS_H_ */
